#!/bin/sh -e

if [ "$ADTTMP" = "" ] ; then
  ADTTMP=`mktemp -d /tmp/bedtools-test.XXXXXX`
fi

# Copy test suite there
cp -a /usr/share/bedtools/test $ADTTMP

# Enter the directory and run the tests
cd $ADTTMP/test
DATA=/usr/share/bedtools/data BT=/usr/bin/bedtools sh test.sh | tee test.sh.output

# Did it fail ?
TESTFAILED=0
grep -q fail test.sh.output && TESTFAILED=1

# Clean
cd
rm -rf $ADTTMP/test

exit $TESTFAILED
